import type { KnowledgeGraphInput } from '../lib/types';

export const sampleGraph: KnowledgeGraphInput = {
  nodes: [
    {
      id: 'ml',
      type: 'Concept',
      label: 'Machine Learning',
      description: 'A subset of AI that enables systems to learn from data',
      field: 'Computer Science',
      established: '1959',
    },
    {
      id: 'dl',
      type: 'Concept',
      label: 'Deep Learning',
      description: 'ML using multi-layered neural networks',
      breakthrough_year: '2012',
    },
    {
      id: 'nn',
      type: 'Technology',
      label: 'Neural Networks',
      description: 'Computing systems inspired by biological neural networks',
      layers: 'input, hidden, output',
    },
    {
      id: 'cnn',
      type: 'Technology',
      label: 'CNN',
      description: 'Convolutional Neural Networks for image processing',
      use_case: 'Computer Vision',
    },
    {
      id: 'transformer',
      type: 'Technology',
      label: 'Transformer',
      description: 'Attention-based architecture for sequence modeling',
      paper: 'Attention Is All You Need',
      year: '2017',
    },
    {
      id: 'llm',
      type: 'Technology',
      label: 'Large Language Models',
      description: 'Massive transformer models trained on text data',
      examples: 'GPT, Claude, Llama',
    },
    {
      id: 'supervised',
      type: 'Process',
      label: 'Supervised Learning',
      description: 'Training with labeled data',
      input: 'labeled dataset',
    },
    {
      id: 'unsupervised',
      type: 'Process',
      label: 'Unsupervised Learning',
      description: 'Finding patterns in unlabeled data',
      techniques: 'clustering, dimensionality reduction',
    },
    {
      id: 'rl',
      type: 'Process',
      label: 'Reinforcement Learning',
      description: 'Learning through trial, error, and reward signals',
      example: 'AlphaGo',
    },
    {
      id: 'gd',
      type: 'Process',
      label: 'Gradient Descent',
      description: 'Optimization algorithm for training models',
      variants: 'SGD, Adam, AdaGrad',
    },
  ],
  edges: [
    { source: 'ml', target: 'dl', type: 'INCLUDES' },
    { source: 'dl', target: 'nn', type: 'USES' },
    { source: 'nn', target: 'cnn', type: 'VARIANT' },
    { source: 'nn', target: 'transformer', type: 'VARIANT' },
    { source: 'transformer', target: 'llm', type: 'ENABLES' },
    { source: 'ml', target: 'supervised', type: 'PARADIGM' },
    { source: 'ml', target: 'unsupervised', type: 'PARADIGM' },
    { source: 'ml', target: 'rl', type: 'PARADIGM' },
    { source: 'nn', target: 'gd', type: 'TRAINED_WITH' },
    { source: 'dl', target: 'cnn', type: 'INCLUDES' },
    { source: 'dl', target: 'transformer', type: 'INCLUDES' },
  ],
};
